#
# Makefile for Allwinner's sun8i DRM device driver
#

sun8i-de2-drm-objs := de2_drv.o de2_crtc.o de2_plane.o
sun8i-de2-hdmi-objs := de2_hdmi.o de2_hdmi_io.o

obj-$(CONFIG_DRM_SUN8I_DE2) += sun8i-de2-drm.o
obj-$(CONFIG_DRM_SUN8I_DE2_HDMI) += sun8i-de2-hdmi.o
